#############################################################################
# Makefile for building: Win32/Release/Listening_Test.app/Contents/MacOS/Listening_Test
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Listening_Test.pro
# Template: app
# Command: /Users/kukdh1/Qt/5.7/clang_64/bin/qmake -spec macx-xcode -o Listening_Test.xcodeproj/project.pbxproj Listening_Test.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/kukdh1/Qt/5.7/clang_64/bin/moc
UIC       = /Users/kukdh1/Qt/5.7/clang_64/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DLL -DQT_WIDGETS_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -IGeneratedFiles -I. -IGeneratedFiles/Release -I../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -IGeneratedFiles/release -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -IGeneratedFiles -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/kukdh1/Qt/5.7/clang_64/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: GeneratedFiles/qrc_MainWindow.cpp GeneratedFiles/release/moc_MainWindow.cpp GeneratedFiles/ui_MainWindow.h GeneratedFiles/ui_Progress.h
compiler_rcc_make_all: GeneratedFiles/qrc_MainWindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) GeneratedFiles/qrc_MainWindow.cpp
GeneratedFiles/qrc_MainWindow.cpp: MainWindow.qrc \
		../../../Qt/5.7/clang_64/bin/rcc
	/Users/kukdh1/Qt/5.7/clang_64/bin/rcc -name MainWindow MainWindow.qrc -o GeneratedFiles/qrc_MainWindow.cpp

compiler_moc_header_make_all: GeneratedFiles/release/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) GeneratedFiles/release/moc_MainWindow.cpp
GeneratedFiles/release/moc_MainWindow.cpp: GeneratedFiles/ui_MainWindow.h \
		GeneratedFiles/ui_Progress.h \
		Model.h \
		Audio.h \
		MainWindow.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/kukdh1/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/kukdh1/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/kukdh1/Documents/Xcode/Listening_Test -I/Users/kukdh1/Documents/Xcode/Listening_Test/GeneratedFiles -I/Users/kukdh1/Documents/Xcode/Listening_Test -I/Users/kukdh1/Documents/Xcode/Listening_Test/GeneratedFiles/Release -I/Users/kukdh1/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/kukdh1/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/kukdh1/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/kukdh1/Qt/5.7/clang_64/lib MainWindow.h -o GeneratedFiles/release/moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: GeneratedFiles/ui_MainWindow.h GeneratedFiles/ui_Progress.h
compiler_uic_clean:
	-$(DEL_FILE) GeneratedFiles/ui_MainWindow.h GeneratedFiles/ui_Progress.h
GeneratedFiles/ui_MainWindow.h: MainWindow.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/kukdh1/Qt/5.7/clang_64/bin/uic MainWindow.ui -o GeneratedFiles/ui_MainWindow.h

GeneratedFiles/ui_Progress.h: Progress.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/kukdh1/Qt/5.7/clang_64/bin/uic Progress.ui -o GeneratedFiles/ui_Progress.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

