# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Audio.h \
    ./Model.h \
    ./MainWindow.h
SOURCES += ./Audio.cpp \
    ./main.cpp \
    ./MainWindow.cpp \
    ./Model.cpp
FORMS += ./MainWindow.ui \
    ./Progress.ui
RESOURCES += MainWindow.qrc
